# ----
# Site

title: "Pokémon TCG API Documentation"
description: "Documentation for the Pokémon TCG API at pokemontcg.io"
url: https://docs.pokemontcg.io
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api_v2:
    title: API v2
    position: 2
  api_v1:
    title: API v1 (Deprecated)
    position: 3
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
